/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Clientes: () => import('#controllers/clientes_controller'),
  Pedidos: () => import('#controllers/pedidos_controller'),
  Produtos: () => import('#controllers/produtos_controller'),
}
