/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ClienteSchema extends BaseModel {
  static $columns = ['criadoEm', 'id', 'modificadoEm', 'nome', 'telefone'] as const
  $columns = ClienteSchema.$columns
  @column.dateTime()
  declare criadoEm: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare modificadoEm: DateTime | null
  @column()
  declare nome: string
  @column()
  declare telefone: string
}

export class ItensPedidoSchema extends BaseModel {
  static $columns = ['criadoEm', 'id', 'modificadoEm', 'pedidoId', 'precoTotal', 'precoUnitario', 'produtoId', 'quantidade'] as const
  $columns = ItensPedidoSchema.$columns
  @column.dateTime()
  declare criadoEm: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare modificadoEm: DateTime | null
  @column()
  declare pedidoId: number
  @column()
  declare precoTotal: string
  @column()
  declare precoUnitario: string
  @column()
  declare produtoId: number
  @column()
  declare quantidade: number
}

export class PedidoSchema extends BaseModel {
  static $columns = ['clienteId', 'criadoEm', 'id', 'modificadoEm', 'status', 'valorTotal'] as const
  $columns = PedidoSchema.$columns
  @column()
  declare clienteId: number
  @column.dateTime()
  declare criadoEm: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare modificadoEm: DateTime | null
  @column()
  declare status: string
  @column()
  declare valorTotal: string
}

export class ProdutoSchema extends BaseModel {
  static $columns = ['ativo', 'criadoEm', 'id', 'modificadoEm', 'nome', 'preco'] as const
  $columns = ProdutoSchema.$columns
  @column()
  declare ativo: boolean
  @column.dateTime()
  declare criadoEm: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare modificadoEm: DateTime | null
  @column()
  declare nome: string
  @column()
  declare preco: string
}
